# Generated by Django 4.1.2 on 2022-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('matcodigo', models.AutoField(primary_key=True, serialize=False)),
                ('matmatricula', models.IntegerField(blank=True, null=True)),
                ('matpessoa', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'matriculas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('precodigoint', models.AutoField(primary_key=True, serialize=False)),
                ('prematmatricula', models.IntegerField(blank=True, null=True)),
                ('prematpessoa', models.CharField(blank=True, max_length=45, null=True)),
                ('predata', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'presenca',
                'managed': False,
            },
        ),
    ]
